exchange/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("search", views.search, name="search"),
    path("add-department/<int:univ>", views.addDepartment, name="add-department"),
    path("edit-department/<int:dep>", views.editDepartment, name="edit-department"),
    path("home", views.home),
    path("university/<int:id>", views.university),
    path("review-exchange", views.reviewExchange, name="review-exchange"),
    path("continent/<str:continent>", views.countries, name="countries"),
    path("country/<int:country>", views.cities, name="cities"),
    path("city/<int:id>", views.universities, name="universities"),
    path("edit/<int:univ>", views.edit, name="edit"),
    path(
        "edit-department-student/<int:univ>/<int:stud>",
        views.editDepartmentStudent,
        name="edit-department-student",
    ),
    path(
        "edit-exchange/<int:univ>/<int:stud>", views.editExchange, name="edit-exchange"
    ),
    path(
        "edit-financial/<int:univ>/<int:exch>",
        views.editFinancial,
        name="edit-financial",
    ),
    path("login", views.exchangeLogin, name="exchange-login"),
    path("logout", views.exchangeLogout, name="exchange-logout"),
    path("rapport", views.rapport),
    path("base", views.base),
    path("user", views.user),
    path("review", views.review),
    path("", views.index),
]

mobility/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("exchange.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
]

exchange/models.py
from django.db import models

from .consts import *


class Country(models.Model):
    name = models.CharField(max_length=100)
    continent = models.CharField(max_length=30, choices=CONTINENTS)
    ECTSConversion = models.FloatField(
        default=0
    )  # 1 crédit du pays concerné vaut x crédits ECTS

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey("Country", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class University(models.Model):
    name = models.CharField(max_length=1000)
    city = models.ForeignKey("City", on_delete=models.CASCADE)
    website = models.URLField(blank=True)

    # Utilisation des coordonnées pour afficher les POI sur la carte interactive
    latitude = models.DecimalField(
        max_digits=11, decimal_places=6, null=True, blank=True
    )
    longitude = models.DecimalField(
        max_digits=11, decimal_places=6, null=True, blank=True
    )

    rank_metric = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    life_metric = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    CWUR_rank = models.IntegerField(null=True, blank=True)

    demand = models.IntegerField(default=0)
    project = models.BooleanField(default=False)
    can_split_year = models.BooleanField(default=False)

    # TODO : make a ManyToManyField out of this mess
    AvailableForBS = models.BooleanField(default=False)
    AvailableForGCU = models.BooleanField(default=False)
    AvailableForGE = models.BooleanField(default=False)
    AvailableForGEN = models.BooleanField(default=False)
    AvailableForGI = models.BooleanField(default=False)
    AvailableForGM = models.BooleanField(default=False)
    AvailableForIF = models.BooleanField(default=False)
    AvailableForSGM = models.BooleanField(default=False)
    AvailableForTC = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ExchangeOffer(models.Model):
    university = models.ForeignKey("University", on_delete=models.CASCADE)
    duration = models.CharField(max_length=200, choices=DURATION)
    available_places = models.IntegerField(default=0)
    exclusive = models.BooleanField(default=False)

    def __str__(self):
        return str(self.pk)


# TODO : merge admin and student into one class
class UniversityContractAdmin(models.Model):
    contract_type = models.CharField(max_length=200, choices=CONTRACTS, default="X")
    university = models.ForeignKey("University", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.contract_type) + " at " + self.university.name


class UniversityContractStudent(models.Model):
    contract_type = models.CharField(max_length=200, choices=CONTRACTS, default="X")
    university = models.ForeignKey("University", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.contract_type) + " at " + self.university.name


class UniversityLanguages(models.Model):
    university = models.ForeignKey("University", on_delete=models.CASCADE)
    language = models.CharField(max_length=50, default="")
    diploma_language = models.CharField(
        max_length=200,
        null=True,
        blank=True,
    )
    language_level = models.CharField(
        max_length=10,
        choices=LEVEL,
        null=True,
        blank=True,
        default="X",
    )

    def __str__(self):
        return str(self.language) + " for " + self.university.name


class Department(models.Model):
    university = models.ForeignKey("University", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="")
    rank = models.IntegerField(
        default=1,
        help_text="Utilisez une valeur entre 1 et 5, 1 étant la plus basse et 5 la plus haute.",
    )

    class Meta:
        permissions = (
            ("noter_depart", "Creer et noter un département d'une université"),
        )

    def __str__(self):
        return str(self.name) + " at " + self.university.name


class Student(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(
        default="prenom.nom@insa-lyon.fr",
        help_text="Utilisez votre adresse INSA : prenom.nom@insa-lyon.fr",
    )

    INSA_department = models.CharField(max_length=10, choices=DEPARTMENT)
    nationality = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return "[" + str(self.INSA_department) + "]" + str(self.email)


class FinancialAid(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    amount = models.IntegerField(null=True, blank=True, default=0)
    received_every = models.CharField(
        max_length=15, null=True, blank=True, choices=RECEIVED_EVERY
    )
    exchange = models.ForeignKey("Exchange", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Exchange(models.Model):
    university = models.ForeignKey("University", on_delete=models.CASCADE)
    student = models.ForeignKey("Student", on_delete=models.CASCADE)

    year = models.IntegerField(default=4, choices=YEAR_CHOICE)
    semester = models.IntegerField(default=1, choices=SEMESTER_CHOICE)
    start_date = models.DateField()
    end_date = models.DateField()

    visa = models.BooleanField(default=False)
    visa_months = models.IntegerField(null=True, blank=True, default=0)
    visa_weeks = models.IntegerField(null=True, blank=True, default=0)
    visa_days = models.IntegerField(null=True, blank=True, default=0)

    comment = models.CharField(max_length=10000, null=True, blank=True)
    rent = models.IntegerField(null=True, blank=True, default=0)
    monthly_expenses = models.IntegerField(null=True, blank=True, default=0)

    night_life_grade = models.IntegerField(
        null=True, blank=True, default=0, choices=GRADE
    )
    cultural_life_grade = models.IntegerField(
        null=True, blank=True, default=0, choices=GRADE
    )
    security_grade = models.IntegerField(
        null=True, blank=True, default=0, choices=GRADE
    )

    def __str__(self):
        return str(self.student) + " at " + self.university.name

exchange/forms.py
from django import forms

from .models import (
    Student,
    UniversityLanguages,
    Department,
    Exchange,
    FinancialAid,
    Country,
    UniversityContractStudent,
    University,
    ExchangeOffer,
)


# ---------------------- AJOUT D'INFO------------------------
# Rajoute rInfo1 - Student
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"
        labels = {
            "name": "Prénom",
            "surname": "Nom de famille",
            "INSA_department": "Département INSA",
            "nationality": "Nationalité",
        }


# RajouterInfo2 - Language
class LangueForm(forms.ModelForm):
    class Meta:
        model = UniversityLanguages
        exclude = ("university",)


# RajouterInfo2 -  Departement
class DepForm(forms.Form):
    GRADE = ((0, "------"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"))

    NameDep = forms.ModelChoiceField(
        queryset=Department.objects.none(),
        label="département de l'université dans lequel l'échange a été effectué",
        required=False,
    )
    Note = forms.ChoiceField(
        choices=GRADE,
        required=False,
        label="Note du département (/5)",
        help_text="Notez la qualité de l'enseignement (5 étant la note la plus haute)",
    )

    def __init__(self, qs, *args, **kwargs):
        super(DepForm, self).__init__(*args, **kwargs)
        self.fields["NameDep"].queryset = qs


# RajouterInfo3 - Exchange
class ExchForm(forms.ModelForm):
    class Meta:
        model = Exchange
        exclude = (
            "student",
            "university",
            "visa",
        )
        widgets = {"comment": forms.Textarea(attrs={"cols": 80, "rows": 10})}


# RajouterInfo3 - Exchange (case à cocher)
# TODO : virer ce form qui ne devrait pas exister..
class ExchFormVisa(forms.ModelForm):
    class Meta:
        model = Exchange
        fields = ("visa",)


# RajouterInfo4 - Aides Finances
class FinancialForm(forms.ModelForm):
    class Meta:
        model = FinancialAid
        exclude = ("exchange",)
        labels = {
            "name": ("Nom de la bourse"),
            "amount": ("Valeur de la bourse (en €)"),
            "received_every": (
                "S'agit-il d'une valeur mensuelle, hebdomadaire ou journalière ?"
            ),
        }


# -----------------RECHERCHE AVANCEE-------------------
# Filtre : continent
class RAcontinentForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ("continent",)


# Filtre : Contract
class ContractForm(forms.ModelForm):
    CONTRACTS = (("", "---------"), ("DD", "Double Diplome"), ("M", "Mobilite"))
    ContractType = forms.ChoiceField(
        choices=CONTRACTS, required=False, label="Type de contrat avec l'INSA"
    )

    class Meta:
        model = UniversityContractStudent
        fields = ["contract_type"]


# Ordonage :
class OrdreForm(forms.Form):
    ORDRES = (
        ("", "------"),
        ("rank_metric", "Ranking"),
        ("life_metric", "Qualité de Vie"),
        ("name", "Pays"),
        ("CWUR_rank", "Ranking Mondial"),
        ("demand", "Demande"),
    )
    Ordre = forms.ChoiceField(
        choices=ORDRES, widget=forms.Select(attrs={"class": "required"})
    )


# ------------------PROF: MOFIFIE----------------
# RajouterInfo2 - Department
class DepartForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = (
            "name",
            "rank",
        )
        labels = {
            "name": (
                "Nom du département de l'université dans lequel l'échange a été effectué"
            ),
            "rank": ("Note du département (/5)"),
        }


# Modifie Infos Université
class UnivForm(forms.ModelForm):
    class Meta:
        model = University
        fields = ("demand",)
        labels = {"demand": "Nombre de demandes (en moyenne)"}


class UnivPlacesForm(forms.ModelForm):
    class Meta:
        model = ExchangeOffer
        fields = ("available_places",)
        labels = {"available_places": "Nombre de places"}

templates/exchange/addDepartment.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block head%}
<title> Ajout Of </title>
{% endblock head %}

{% block intro %}
<div id="intro" style="min-height: 0vh;">
    <ul class="actions">
        <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
    </ul>
</div>
{% endblock intro %}

{% block main %}
<!-- Post -->
<section class="post">
    <header class="major">
        <h1>Ajouter une information officielle</h1>
    </header>
    <div class="image main"><img alt="" src="images/pic01.jpg" /></div>
</section>
<section>
    <div class="table-wrapper">
        <h3>Départements déjà existants:</h3>
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Classement</th>
                    <th>Modifier</th>
                </tr>
            </thead>
            <tbody>
                {% for d in departs %}
                <tr>
                    <td>{{d.name}}</td>
                    <td>{{d.rank}}</td>
                    <td><a href="{% url "edit-department" d.id %}">#</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    <div class="table-wrapper">
        <h3>Ajouter un département</h3>
        <form action="{% url 'add-department' Uni.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Ajouter">
        </form>
    </div>
    </hr>
    <hr>
    <div class="table-wrapper">
        <h3>Modifier les infos de {{Uni.name}}</h3>
        <form action="{% url 'add-department' Uni.id %}" method="post">
            {% csrf_token %}
            {{ formUni.as_p }}
            <input type="submit" value="Modifier">
        </form>
    </div>
    <!-- TODO: lol -->
    <div class="table-wrapper">
        <form action="/university/{{Uni.id}}" method="get">
            <input type="submit" value="Retour sur la page de l'université">
        </form>
    </div>
    </hr>
</section>
{% endblock main %}

templates/exchange/addInformation.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Espace Etudiant</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <h1>Retour<br/>
        d'échange</h1>
        <p></p>
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul> 
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h2>Informations</h2>
    </header>
    
    <div height="20rem" id="centralsection">

    </div>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}

templates/exchange/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Massively by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
    <style>
    {% block style %}
    {% endblock style %}
    </style>
	<head>
        {% block head%}
        {% endblock head %}
		<meta charset="utf-8" />
        <meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport" />
        <link href="{% static 'exchange/images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon"/>
		<link href="{% static 'exchange/assets/css/main.css' %}" rel="stylesheet" type="text/css" />
		<noscript><link href="{% static 'exchange/assets/css/noscript.css' %}" rel="stylesheet" type="text.css" /></noscript>
    </head>

    <body class="is-preload">
        <div id="wrapper">

            {% block intro %}
            {% endblock intro %}

            <!--Bouton pour retourner à l'accueil
            <header id="header">
            </header>
            -->
            <!--Barre de navigation-->
            <nav id="nav">
                <ul class="links">
                    <li class="accueil">
                        <a href="/home">
                            <img id="home-icon-desktop" src="{% static 'exchange/images/HomeIconWhite.png' %}" style="height:3em;margin-top:15px;"></img> <!-- 1em = 16px -->
                            <!-- <img id="home-icon-mobile" src="{% static 'exchange/images/HomeIconBlack.png' %}" style="height:3em;margin-top:15px;"></img> --> <!-- 1em = 16px -->
                            <!--Ajouter "margin-right: 1em;" dans style si on décommente les lignes suivantes-->
                            <!--
                            <span style="float:right; display: block; align: middle;">
                                <span>Accueil</span>
                            </span>
                            -->
                        </a>
                    </li>
                    <li><a href="/search">Rechercher</a></li>
                    <li><a href="/review-exchange">Ajouter une info</a></li>
                    <!--
                    {% if user.is_authenticated %}
                    <li><a href="/logout">Déconnexion</a></li>
                    {% else %}
                    <li><a href="/login">Connexion</a></li>
                    {% endif %}
                    -->
                </ul>
            </nav>

            <!--Main = gros rectangle blanc-->
            <div id="main">
                {% block main %}
                {% endblock main %}
            </div>

            <!--Bas de page-->
            <div id="copyright">
                <ul><li>&copy; <a href="https://www.facebook.com/mieuxquetcmemes/">Astus International</a></li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li></ul>
            </div>

        </div>
        
        <!-- Scripts -->
		<script src="{% static 'exchange/assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'exchange/assets/js/jquery.scrollex.min.js' %}"></script>
		<script src="{% static 'exchange/assets/js/jquery.scrolly.min.js' %}"></script>
		<script src="{% static 'exchange/assets/js/browser.min.js' %}"></script>
		<script src="{% static 'exchange/assets/js/breakpoints.min.js' %}"></script>
		<script src="{% static 'exchange/assets/js/util.js' %}"></script>
		<script src="{% static 'exchange/assets/js/main.js' %}"></script>
        <!--<script src="{% static 'exchange/assets/js/jquery3.min.js' %}"></script>-->
        <script src="{% static 'exchange/assets/js/jquery.rateyo.js' %}"></script>
        <script>
        {% block scripts %}
        {% endblock scripts %}
        </script>
    </body>
</html>

templates/exchange/countries.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Pays</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul>
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h1>Ajouter<br />
        une info</h1>
        <p>Donne ton avis sur ton échange à l'étranger</p>
    </header>
    <div class="table-wrapper">
        <header>
            <h3>Pays</h3>
        </header>
        <table>
            <tbody>
                {% for p in pays_var %}
                <tr>
                    <td><a href=/country/{{p.id}}>{{p.name}}</a></td>
                </tr> 
                {% endfor %}                                                                            
            </tbody>
        </table>
    </div>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}

templates/exchange/edit.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Ajouter une info - Université</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul>
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h1>Ajouter<br />
        une info</h1>
        <p>Donne ton avis sur ton échange à l'étranger</p>
    </header>

    <div class="table-wrapper">
        <header>
            <h3>Informations personnelles</h3>
        </header>
        <form action="{% url 'edit' uni.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Continuer">
        </form>
    </div>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}

templates/exchange/editDepartment.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Modif Of</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul>
    </div>
{% endblock intro %}

{% block main %}
    <!-- Post -->
    <section class="post">
        <header class="major">
            <h1>Département {{depart.name}}</h1>
        </header>
        <div class="image main"><img alt="" src="images/pic01.jpg" /></div>
    </section>
    <section>
        <div class="table-wrapper">
            <h3>Modifiez un département de {{depart.university.name}}</h3>
            <form action="{% url 'edit-department' depart.id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Modify">
            </form>
        </div>
    </section>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}

templates/exchange/editDepartmentStudent.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Ajouter une info - Departement</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul>
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h1>Ajouter<br/>
            une info</h1>
        <p>Donne ton avis sur ton échange à l'étranger</p>
    </header>

    <div class="table-wrapper">
        <header>
            <h3>Informations sur l'université</h3>
        </header>
        <form action="{% url 'edit-department-student' Uni.id Stud.id %}" method="post">
            {% csrf_token %}
            {{ formDep.as_p }}

            <h3>Informations Langue</h3>
            <label for="{{ form2.language.id_for_label }}">Langue des cours</label>
            {{ form2.language }}
            <i>Si vous n'avez pas passé de certification, cliquez sur "Continuer"</i>
            <br \>

            <label for="{{ form2.diploma_language.id_for_label }}">Quelle certification linguistique avez-vous dû passer ?
                ?</label>
            {{ form2.diploma_language }}
            <br \>

            <label for="{{ form2.language_level.id_for_label }}">Quel niveau avez-vous dû certifier ?</label>
            {{ form2.language_level }}
            <br \>
            <input type="submit" value="Continuer">
        </form>
    </div>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}

templates/exchange/search.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
    .required:after {
        content:" *";
        color: red;
    }
    .required_before:before {
        content:"* ";
        color: red;
    }
{% endblock style %}

{% block head %}
    <title>Recherche Avancée</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul>
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h1>Recherche Avancée</h1>
        <p>Recherchez une université en fonction de filtres</p>
    </header>

    <div class="table-wrapper">
        <header><h3>Filtrer les Universitées selon:</h3></header>
        <form action="{% url 'search' %}"  method="post">
            {% csrf_token %}
            <label class="required" for="id_continent">continent&nbsp;:</label>
            <select id="id_continent" name="continent" onchange="myFunction()" required="">
                <option selected="" value="">---------</option>
                <option value="AS">Asie</option>
                <option value="AF">Afrique</option>
                <option value="AdN">Amerique du Nord</option>
                <option value="AdS">Amerique du Sud</option>
                <option value="EU">Europe</option>
                <option value="OC">Oceanie</option>
            </select>
            <br />
            <label for="id_name">Pays&nbsp;:</label>
            <select id="testt" name="name">
                <option value="" >---------</option>  
                {% for c in ttl %}
                <option id="{{c.ID}}" style="display:none;" value="{{ c.name }}">{{ c.name }}</option>
                {% endfor %}
            </select>

            <br />
            {{ formContract.as_p }}
            <hr>
            <h3>Ordonner les Universités selon:</h3>
            <label class="required" for="id_Ordre">Ordre&nbsp;:</label>
            <select id="id_Ordre" name="Ordre" required="">
                <option selected="" value="">---------</option>
                <option value="rank_metric">Ranking</option>
                <option value="life_metric">Qualité de Vie</option>
                <option value="name">Pays</option>
                <option value="CWUR_rank">Ranking Mondial</option>
                <option value="demand">Demande</option>
            </select>
            <br />
            </hr>
            <input id="buton" type="submit" value="Rechercher">
        </form>
    </div>
    {% if valide %}
    <div class="table-wrapper">
        <h3>Liste des universités</h3>
        <p>Nombre d'éléments trouvés : {{universitiesC.count}}</p>
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Note du département</th>
                    <th>Qualité de vie</th>
                    <th>Ville</th>
                    <th>Pays</th>
                    <th>Demande</th>
                    <th>Type de contrat avec l'INSA</th>

                </tr>
            </thead>
            <tbody>
                {% for u in universitiesC %}
                <tr>
                    <td><a href=/university/{{u.university.id}}>{{u.university.name}}</a></td>
                    <td>{{u.university.rank_metric}}</td>
                    <td>{{u.university.life_metric}}</td>
                    <td>{{u.university.city.name}}</td>
                    <td>{{u.university.city.country.name}}</td>
                    <td>{{u.university.demand}}</td>
                    <td>{{u.get_contract_type_display}}</td>
                </tr>
                {% endfor %}                                        
            </tbody>
        </table>
    </div>
    {% endif %}
    <p class="required_before" style="font-size:12px;"> - Champ requis</p>
{% endblock main %}

{% block scripts %}
    function myFunction() {
        //on prend le continent saisi par utilisatuer
        var cont = document.getElementById("id_continent").value
        console.log(cont)

        //on commence par cacher tout les pays
        {% for c in ttl %}
            if(cont == "{{c.continent}}"){
                document.getElementById("{{c.id}}").setAttribute('style', 'display:block;');
            }else{
                document.getElementById("{{c.id}}").setAttribute('style', 'display:none;');
            }
        {% endfor %}
        
    }
{% endblock scripts %}

templates/exchange/universities.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Universités</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul>
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h1>Ajouter<br />
        une info</h1>
        <p>Donne ton avis sur ton échange à l'étranger</p>
    </header>

    <div class="table-wrapper">
        <header>
            <h3>Université</h3>
        </header>
        <table>
            <tbody>
                {% for uni in univ %}
                <tr>
                    <td><a href=/edit/{{uni.id}}>{{uni.name}}</a></td>
                </tr> 
                {% endfor %}                                                                            
            </tbody>
        </table>
    </div>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}

templates/exchange/user.html
{% extends 'exchange/base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block head %}
    <title>Espace Etudiant</title>
{% endblock head %}

{% block intro %}
    <div id="intro" style="min-height: 0vh;">
        <h1>Espace<br/>
        Etudiant</h1>
        <p></p>
        <ul class="actions">
            <li><a class="button icon solo fa-arrow-down scrolly" href="#nav">Continue</a></li>
        </ul> 
    </div>
{% endblock intro %}

{% block main %}
    <header class="major">
        <h2>TEST</h2>
    </header>
    
    <div height="20rem" id="centralsection">

    </div>
{% endblock main %}

{% block scripts %}
{% endblock scripts %}